x=input("Enter your first number: ")
y=input("Enter your second number: ")
print("First operation is '+': ")
print(x+y)
print(int(x)+int(y))
print("Second operation is '-': ")
print(int(x)-int(y))
print("Third operation is '*': ")
print(int(x)*int(y))
print("Forth operation is '/': ")
print(int(x)/int(y))
print("Fifth operation is '//': ")
print(int(x)//int(y))
print("Sixth operation is '%': ")
print(int(x)%int(y))
print("hope that it helped you, good luck for you journey!!")